BEGIN;

-- Categorías aprobadas.
INSERT INTO categories (name) VALUES
    ('none'),
    ('fiction'),
    ('fantasy'),
    ('science_fiction'),
    ('mystery'),
    ('thriller'),
    ('romance'),
    ('horror'),
    ('adventure'),
    ('history'),
    ('biography'),
    ('science'),
    ('technology'),
    ('self_help'),
    ('children'),
    ('comics');

-- Autores del catálogo semilla.
INSERT INTO authors (full_name) VALUES
    ('Elena Marín'),
    ('Tomás Rivera'),
    ('Lucía Ferrer'),
    ('Mateo Salcedo'),
    ('Sofía Beltrán'),
    ('Adriana Solís'),
    ('Nicolás Varela'),
    ('Camila Duarte'),
    ('Bruno Alcázar'),
    ('Irene Valdés'),
    ('Daniel Rojas'),
    ('Paula Cedeño'),
    ('Sebastián Mora'),
    ('Valeria Núñez'),
    ('Gabriel Pardo'),
    ('Marina Lozano'),
    ('Esteban Gil'),
    ('Clara Mendieta'),
    ('Héctor Linares'),
    ('Andrea Ponce'),
    ('Ricardo Sanz'),
    ('Natalia Cruz'),
    ('Javier Montero'),
    ('Daniela Fuentes'),
    ('Óscar Leiva'),
    ('Carolina Méndez'),
    ('Luisana Ortega'),
    ('Renata Silva'),
    ('Martín Acosta'),
    ('Elisa Moreno'),
    ('Iván Tejada'),
    ('Gabriela Santos'),
    ('Mauricio Peña'),
    ('Verónica Ríos'),
    ('Samuel Cárdenas'),
    ('Diego Herrera'),
    ('Alicia Navarro'),
    ('Pablo Escobar Ruiz'),
    ('Lorena Castillo'),
    ('Emilio Suárez'),
    ('Rafael Zamora'),
    ('María Eugenia Torres'),
    ('Andrés Villalba'),
    ('Patricia León'),
    ('Fernando Robles'),
    ('Mónica Vidal'),
    ('Carlos Méndez'),
    ('Laura Benítez'),
    ('Jorge Alvarado'),
    ('Ana Lucía Prado'),
    ('Eduardo Pineda'),
    ('Silvia Contreras'),
    ('Rodrigo Méndez'),
    ('Teresa Molina'),
    ('Hugo Santamaría'),
    ('Kevin Andrade'),
    ('Andrea Campos'),
    ('Miguel Arroyo'),
    ('Laura Serrano'),
    ('Sergio Palma'),
    ('Daniela Rivas'),
    ('Mario Espinosa'),
    ('Paola Guerra'),
    ('Cristina Valle'),
    ('Alejandro Núñez'),
    ('Maribel Soto'),
    ('Pedro Lasso'),
    ('Sara Montenegro'),
    ('Emma Castillo'),
    ('Julio Peralta'),
    ('Raúl Cabrera'),
    ('Beatriz Luna'),
    ('Cristóbal Vera'),
    ('José Miranda'),
    ('Noelia Paredes');

-- Libros y su categoría principal.
WITH seed(category_name, title, author_name, synopsis, price_in_cents, stock) AS (
    VALUES
        ('fiction', 'La ciudad de las ventanas abiertas', 'Elena Marín', 'Una joven regresa a su barrio de infancia y descubre que cada vecino guarda una versión distinta de la misma desaparición.', 1499, 18),
        ('fiction', 'Los días que dejamos en la estación', 'Tomás Rivera', 'Tres desconocidos coinciden cada semana en una estación y terminan cambiando el rumbo de sus vidas.', 1250, 22),
        ('fiction', 'El café de las cinco', 'Lucía Ferrer', 'Una cafetería de barrio se convierte en punto de encuentro para personas que buscan empezar de nuevo.', 1199, 25),
        ('fiction', 'Cartas desde el edificio azul', 'Mateo Salcedo', 'Los residentes de un edificio intercambian cartas anónimas que revelan secretos y reconciliaciones.', 1375, 16),
        ('fiction', 'La última fotografía del verano', 'Sofía Beltrán', 'Una familia intenta reconstruir su historia a partir de una fotografía tomada antes de una separación inesperada.', 1525, 14),
        ('fantasy', 'El reino bajo la lluvia', 'Adriana Solís', 'Una aprendiz de cartógrafa descubre un reino oculto que solo aparece durante las tormentas.', 1699, 20),
        ('fantasy', 'La guardiana de los siete faros', 'Nicolás Varela', 'Una joven debe encender siete faros mágicos antes de que una sombra cubra el archipiélago.', 1750, 15),
        ('fantasy', 'El bosque que recordaba nombres', 'Camila Duarte', 'Un bosque antiguo conserva los nombres de quienes se pierden en él y exige un precio por devolverlos.', 1599, 19),
        ('fantasy', 'Las coronas de ceniza', 'Bruno Alcázar', 'Dos herederos rivales deben unir fuerzas cuando un dragón despierta bajo la capital.', 1825, 12),
        ('fantasy', 'La biblioteca de las lunas', 'Irene Valdés', 'Cada libro de una biblioteca secreta abre una puerta hacia una luna distinta.', 1640, 17),
        ('science_fiction', 'Órbita de silencio', 'Daniel Rojas', 'La tripulación de una estación espacial recibe una señal enviada desde la Tierra cien años en el futuro.', 1899, 13),
        ('science_fiction', 'Memoria de titanio', 'Paula Cedeño', 'Una ingeniera descubre que sus recuerdos fueron copiados dentro de un androide militar.', 1775, 18),
        ('science_fiction', 'El último jardín de Marte', 'Sebastián Mora', 'Una botánica protege el único ecosistema marciano mientras varias corporaciones intentan controlarlo.', 1950, 11),
        ('science_fiction', 'Código Aurora', 'Valeria Núñez', 'Una inteligencia artificial climática comienza a tomar decisiones que ningún gobierno autorizó.', 1820, 16),
        ('science_fiction', 'Los hijos del planeta espejo', 'Gabriel Pardo', 'Una misión encuentra un mundo idéntico a la Tierra, pero habitado por versiones alternativas de sus tripulantes.', 2000, 10),
        ('mystery', 'El reloj de la habitación 12', 'Marina Lozano', 'Un hotel antiguo conserva un reloj detenido exactamente a la hora de una muerte sin resolver.', 1480, 21),
        ('mystery', 'La tinta invisible', 'Esteban Gil', 'Una archivista encuentra mensajes ocultos en periódicos publicados durante cuarenta años.', 1395, 19),
        ('mystery', 'Los pasos del pasillo norte', 'Clara Mendieta', 'Un profesor desaparece de una universidad cerrada por vacaciones y solo quedan huellas en un pasillo sellado.', 1550, 17),
        ('mystery', 'El coleccionista de llaves', 'Héctor Linares', 'Varias llaves antiguas conducen a habitaciones que oficialmente nunca existieron.', 1610, 14),
        ('mystery', 'Niebla sobre Puerto Escondido', 'Andrea Ponce', 'Una periodista investiga la desaparición de un pescador en un pueblo donde nadie admite haberlo conocido.', 1460, 20),
        ('thriller', 'Cuenta regresiva en la bahía', 'Ricardo Sanz', 'Una analista descubre un sabotaje capaz de paralizar el puerto más importante del país.', 1790, 15),
        ('thriller', 'El pasajero número nueve', 'Natalia Cruz', 'Ocho pasajeros despiertan en un tren detenido, aunque el registro indica que viajaban nueve.', 1675, 18),
        ('thriller', 'Protocolo medianoche', 'Javier Montero', 'Un especialista en ciberseguridad recibe una orden secreta para apagar la red eléctrica nacional.', 1840, 13),
        ('thriller', 'La llamada de las 3:17', 'Daniela Fuentes', 'Cada madrugada una mujer recibe llamadas de alguien que conoce detalles de un crimen aún no cometido.', 1595, 20),
        ('thriller', 'Zona de exclusión', 'Óscar Leiva', 'Un fotógrafo entra en una ciudad evacuada y descubre que la amenaza no era la que anunciaron.', 1725, 12),
        ('romance', 'Después de la lluvia', 'Carolina Méndez', 'Dos antiguos amigos se reencuentran para reconstruir una librería dañada por una tormenta.', 1399, 24),
        ('romance', 'Un verano en la avenida central', 'Luisana Ortega', 'Una chef y un músico comparten local durante el verano y terminan mezclando mucho más que sus negocios.', 1450, 19),
        ('romance', 'Las cartas que nunca enviamos', 'Renata Silva', 'Una caja de cartas olvidadas reúne a dos personas que habían renunciado al amor.', 1295, 22),
        ('romance', 'Bajo el mismo balcón', 'Martín Acosta', 'Dos vecinos que discuten a diario descubren que llevan meses ayudándose de forma anónima.', 1375, 21),
        ('romance', 'La promesa del último tren', 'Elisa Moreno', 'Una pareja separada por decisiones familiares acuerda reencontrarse en la misma estación diez años después.', 1520, 16),
        ('horror', 'La casa detrás del manglar', 'Iván Tejada', 'Una familia hereda una casa que aparece más cerca del agua cada noche.', 1680, 14),
        ('horror', 'No mires el espejo rojo', 'Gabriela Santos', 'Un espejo antiguo refleja escenas que ocurrirán al día siguiente, siempre con una víctima distinta.', 1560, 17),
        ('horror', 'El coro del sótano', 'Mauricio Peña', 'Los habitantes de un edificio escuchan voces infantiles bajo un sótano que no figura en los planos.', 1710, 12),
        ('horror', 'La hora sin campanas', 'Verónica Ríos', 'En un pueblo remoto, todas las campanas callan antes de que alguien desaparezca.', 1490, 18),
        ('horror', 'Los huéspedes de la habitación vacía', 'Samuel Cárdenas', 'Un cuidador nocturno descubre que una habitación cerrada sigue recibiendo visitantes.', 1625, 15),
        ('adventure', 'La ruta del volcán dormido', 'Diego Herrera', 'Un grupo de exploradores busca una ciudad perdida bajo las laderas de un volcán que comienza a despertar.', 1730, 20),
        ('adventure', 'El mapa de las corrientes', 'Alicia Navarro', 'Una navegante encuentra un mapa que cambia con las mareas y conduce a una isla desconocida.', 1695, 18),
        ('adventure', 'Tras la sombra del jaguar', 'Pablo Escobar Ruiz', 'Una expedición atraviesa la selva siguiendo pistas dejadas por un naturalista desaparecido.', 1585, 19),
        ('adventure', 'La frontera de hielo', 'Lorena Castillo', 'Dos hermanas emprenden una travesía polar para rescatar a su padre antes del invierno permanente.', 1860, 13),
        ('adventure', 'El tesoro de la costa negra', 'Emilio Suárez', 'Un buzo aficionado descubre restos de una flota hundida protegida por una organización clandestina.', 1745, 16),
        ('history', 'Imperios del istmo', 'Rafael Zamora', 'Un recorrido por las culturas, rutas comerciales y conflictos que moldearon el istmo centroamericano.', 2100, 12),
        ('history', 'Ciudades que cambiaron el mundo', 'María Eugenia Torres', 'Una mirada histórica a ciudades cuya política, comercio y cultura transformaron distintas épocas.', 2250, 10),
        ('history', 'Rutas del comercio antiguo', 'Andrés Villalba', 'Explora cómo caravanas, puertos y caminos conectaron civilizaciones durante siglos.', 1975, 14),
        ('history', 'Revoluciones en perspectiva', 'Patricia León', 'Analiza varias revoluciones y sus efectos sociales, económicos y políticos a largo plazo.', 2040, 11),
        ('history', 'La vida cotidiana en la Edad Media', 'Fernando Robles', 'Describe la alimentación, el trabajo, la vivienda y las costumbres de distintos grupos medievales.', 1890, 15),
        ('biography', 'Ada Lovelace: imaginar la máquina', 'Mónica Vidal', 'Biografía accesible sobre la vida, ideas y legado de Ada Lovelace.', 1850, 16),
        ('biography', 'Nikola Tesla: luz y obsesión', 'Carlos Méndez', 'Relato sobre los logros, rivalidades y dificultades personales de Nikola Tesla.', 1920, 14),
        ('biography', 'Marie Curie: dos veces pionera', 'Laura Benítez', 'Recorre la trayectoria científica y humana de Marie Curie.', 1895, 18),
        ('biography', 'Nelson Mandela: una vida de resistencia', 'Jorge Alvarado', 'Síntesis biográfica de la lucha política, prisión y liderazgo de Nelson Mandela.', 2025, 13),
        ('biography', 'Frida Kahlo: pintar el dolor', 'Ana Lucía Prado', 'Explora la vida de Frida Kahlo y la relación entre su experiencia personal y su obra.', 1780, 17),
        ('science', 'El universo en preguntas', 'Eduardo Pineda', 'Explica conceptos de astronomía mediante preguntas sobre galaxias, estrellas, tiempo y materia.', 2150, 15),
        ('science', 'Biología de lo cotidiano', 'Silvia Contreras', 'Relaciona procesos biológicos con situaciones comunes como dormir, comer y enfermarse.', 1999, 18),
        ('science', 'La química que nos rodea', 'Rodrigo Méndez', 'Presenta reacciones químicas presentes en la cocina, el ambiente y el cuerpo humano.', 2060, 16),
        ('science', 'Planeta dinámico', 'Teresa Molina', 'Describe terremotos, volcanes, océanos y cambios geológicos de la Tierra.', 2210, 12),
        ('science', 'Genética sin complicaciones', 'Hugo Santamaría', 'Introduce genes, herencia, mutaciones y biotecnología con ejemplos claros.', 2125, 14),
        ('technology', 'Fundamentos de desarrollo web moderno', 'Kevin Andrade', 'Introduce HTML, CSS, JavaScript, APIs y despliegue de aplicaciones web.', 2499, 20),
        ('technology', 'Bases de datos desde cero', 'Andrea Campos', 'Explica modelado relacional, SQL, índices, transacciones y buenas prácticas.', 2350, 18),
        ('technology', 'Introducción práctica a la ciberseguridad', 'Miguel Arroyo', 'Presenta amenazas comunes, autenticación, cifrado y protección de sistemas.', 2500, 15),
        ('technology', 'Arquitectura de software aplicada', 'Laura Serrano', 'Expone patrones, capas, servicios, escalabilidad y decisiones arquitectónicas.', 2640, 13),
        ('technology', 'Inteligencia artificial para principiantes', 'Sergio Palma', 'Una introducción a aprendizaje automático, redes neuronales y usos responsables.', 2475, 17),
        ('self_help', 'Hábitos que sí permanecen', 'Daniela Rivas', 'Propone un método gradual para construir hábitos realistas y sostenibles.', 1650, 22),
        ('self_help', 'Ordena tu semana', 'Mario Espinosa', 'Guía práctica para priorizar tareas, organizar compromisos y reducir sobrecarga.', 1599, 25),
        ('self_help', 'Aprender a decir no', 'Paola Guerra', 'Explora límites personales, comunicación asertiva y manejo de la culpa.', 1720, 19),
        ('self_help', 'Pequeños pasos, grandes cambios', 'Cristina Valle', 'Ofrece ejercicios sencillos para avanzar en metas personales sin depender de la motivación constante.', 1680, 21),
        ('self_help', 'Calma en días difíciles', 'Alejandro Núñez', 'Reúne estrategias de respiración, reflexión y organización para afrontar momentos de estrés.', 1550, 23),
        ('children', 'Luna y el pez que quería volar', 'Maribel Soto', 'Luna ayuda a un pequeño pez a cumplir su sueño de conocer las nubes.', 999, 30),
        ('children', 'El tren de los animales curiosos', 'Pedro Lasso', 'Un grupo de animales viaja en tren para descubrir por qué desaparecieron los colores del bosque.', 1050, 28),
        ('children', 'Nico y la mochila parlante', 'Sara Montenegro', 'Una mochila mágica enseña a Nico a cuidar sus cosas y ayudar a sus amigos.', 975, 32),
        ('children', 'La nube que tenía miedo de llover', 'Emma Castillo', 'Una nube pequeña aprende que la lluvia también puede traer alegría.', 1025, 27),
        ('children', 'El secreto del jardín brillante', 'Julio Peralta', 'Dos hermanos descubren criaturas diminutas que protegen un jardín durante la noche.', 1100, 25),
        ('comics', 'Centinela Solar: origen', 'Raúl Cabrera', 'Una científica obtiene poderes solares y debe detener una amenaza energética sobre la ciudad.', 1299, 24),
        ('comics', 'Los Guardianes del Metro', 'Beatriz Luna', 'Cuatro jóvenes protegen una red subterránea donde habitan criaturas fantásticas.', 1350, 22),
        ('comics', 'Neón 2099', 'Cristóbal Vera', 'Una mensajera cibernética se enfrenta a corporaciones que controlan los recuerdos.', 1425, 20),
        ('comics', 'Capitán Istmo y la tormenta eterna', 'José Miranda', 'Un héroe controla los vientos para impedir que una tormenta destruya las costas.', 1275, 26),
        ('comics', 'El club de los monstruos amables', 'Noelia Paredes', 'Un grupo de monstruos intenta demostrar que no todos quieren asustar a los humanos.', 1195, 29)
)
INSERT INTO books (title, synopsis, author_id, price_in_cents, stock)
SELECT s.title, s.synopsis, a.id, s.price_in_cents, s.stock
FROM seed s
JOIN authors a ON a.full_name = s.author_name;

WITH seed(category_name, title) AS (
    VALUES
        ('fiction', 'La ciudad de las ventanas abiertas'),
        ('fiction', 'Los días que dejamos en la estación'),
        ('fiction', 'El café de las cinco'),
        ('fiction', 'Cartas desde el edificio azul'),
        ('fiction', 'La última fotografía del verano'),
        ('fantasy', 'El reino bajo la lluvia'),
        ('fantasy', 'La guardiana de los siete faros'),
        ('fantasy', 'El bosque que recordaba nombres'),
        ('fantasy', 'Las coronas de ceniza'),
        ('fantasy', 'La biblioteca de las lunas'),
        ('science_fiction', 'Órbita de silencio'),
        ('science_fiction', 'Memoria de titanio'),
        ('science_fiction', 'El último jardín de Marte'),
        ('science_fiction', 'Código Aurora'),
        ('science_fiction', 'Los hijos del planeta espejo'),
        ('mystery', 'El reloj de la habitación 12'),
        ('mystery', 'La tinta invisible'),
        ('mystery', 'Los pasos del pasillo norte'),
        ('mystery', 'El coleccionista de llaves'),
        ('mystery', 'Niebla sobre Puerto Escondido'),
        ('thriller', 'Cuenta regresiva en la bahía'),
        ('thriller', 'El pasajero número nueve'),
        ('thriller', 'Protocolo medianoche'),
        ('thriller', 'La llamada de las 3:17'),
        ('thriller', 'Zona de exclusión'),
        ('romance', 'Después de la lluvia'),
        ('romance', 'Un verano en la avenida central'),
        ('romance', 'Las cartas que nunca enviamos'),
        ('romance', 'Bajo el mismo balcón'),
        ('romance', 'La promesa del último tren'),
        ('horror', 'La casa detrás del manglar'),
        ('horror', 'No mires el espejo rojo'),
        ('horror', 'El coro del sótano'),
        ('horror', 'La hora sin campanas'),
        ('horror', 'Los huéspedes de la habitación vacía'),
        ('adventure', 'La ruta del volcán dormido'),
        ('adventure', 'El mapa de las corrientes'),
        ('adventure', 'Tras la sombra del jaguar'),
        ('adventure', 'La frontera de hielo'),
        ('adventure', 'El tesoro de la costa negra'),
        ('history', 'Imperios del istmo'),
        ('history', 'Ciudades que cambiaron el mundo'),
        ('history', 'Rutas del comercio antiguo'),
        ('history', 'Revoluciones en perspectiva'),
        ('history', 'La vida cotidiana en la Edad Media'),
        ('biography', 'Ada Lovelace: imaginar la máquina'),
        ('biography', 'Nikola Tesla: luz y obsesión'),
        ('biography', 'Marie Curie: dos veces pionera'),
        ('biography', 'Nelson Mandela: una vida de resistencia'),
        ('biography', 'Frida Kahlo: pintar el dolor'),
        ('science', 'El universo en preguntas'),
        ('science', 'Biología de lo cotidiano'),
        ('science', 'La química que nos rodea'),
        ('science', 'Planeta dinámico'),
        ('science', 'Genética sin complicaciones'),
        ('technology', 'Fundamentos de desarrollo web moderno'),
        ('technology', 'Bases de datos desde cero'),
        ('technology', 'Introducción práctica a la ciberseguridad'),
        ('technology', 'Arquitectura de software aplicada'),
        ('technology', 'Inteligencia artificial para principiantes'),
        ('self_help', 'Hábitos que sí permanecen'),
        ('self_help', 'Ordena tu semana'),
        ('self_help', 'Aprender a decir no'),
        ('self_help', 'Pequeños pasos, grandes cambios'),
        ('self_help', 'Calma en días difíciles'),
        ('children', 'Luna y el pez que quería volar'),
        ('children', 'El tren de los animales curiosos'),
        ('children', 'Nico y la mochila parlante'),
        ('children', 'La nube que tenía miedo de llover'),
        ('children', 'El secreto del jardín brillante'),
        ('comics', 'Centinela Solar: origen'),
        ('comics', 'Los Guardianes del Metro'),
        ('comics', 'Neón 2099'),
        ('comics', 'Capitán Istmo y la tormenta eterna'),
        ('comics', 'El club de los monstruos amables')
)
INSERT INTO books_categories (book_id, category_id)
SELECT b.id, c.id
FROM seed s
JOIN books b ON b.title = s.title
JOIN categories c ON c.name = s.category_name;

COMMIT;
